# Generated by Django 4.1.13 on 2024-08-20 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uni',
            options={'ordering': ['uni']},
        ),
    ]
